holidays:
  1:
    - 1   # 元旦
    - 23  # 除夕彈性
    - 24  # 除夕
    - 27  # 春節
    - 28  # 春節
    - 29  # 春節
  2:
    - 28  # 228
  4:
    - 2   # 兒童節
    - 3   # 清明
  5:
    - 1   # 勞動節
  6:
    - 25  # 端午節
    - 26  # 端午彈性
  10:
    - 1   # 中秋節
    - 2   # 中秋彈性
    - 9   # 國慶日
makeup_days:
  2:
    - 15  # 春節補班
  6:
    - 20  # 端午補班
  9:
    - 26  # 中秋補班
