holidays:
  1:
    - 1   # 元旦

  2:
    - 10  # 除夕彈性
    - 11  # 除夕
    - 12  # 春節
    - 15  # 春節
    - 16  # 春節
  3:
    - 1   # 228 補假
  4:
    - 2   # 兒童節補假
    - 5   # 清明補假
  5:
    - 1   # 勞動節
  6:
    - 14  # 端午節
  9:
    - 20  # 中秋節彈性
    - 21  # 中秋節
  10:
    - 11  # 國慶日補假
  12:
    - 31  # 元旦補假
makeup_days:
  2:
    - 20  # 春節補班
  9:
    - 11  # 中秋補班
