holidays:
  1:
    - 31  # 除夕

  2:
    - 1   # 春節
    - 2   # 春節
    - 3   # 春節
    - 4   # 春節
    - 28  # 228
  4:
    - 4   # 兒童節
    - 5   # 清明
  5:
    - 2   # 勞動節補假
  6:
    - 3   # 端午節
  9:
    - 9   # 中秋節補假
  10:
    - 10  # 國慶日
makeup_days:
  1:
    - 22  # 春節補班
