holidays:
  1:
    - 2   # 元旦
    - 20  # 春節彈性
    - 23  # 春節
    - 24  # 春節
    - 25  # 春節
    - 26  # 春節
    - 27  # 春節彈性

  2:
    - 27  # 228 彈性
    - 28  # 228
  4:
    - 3   # 清明彈性
    - 4   # 清明
    - 5   # 清明
  5:
    - 1   # 勞動節
  6:
    - 22  # 端午節
    - 23  # 端午節彈性
  9:
    - 29  # 中秋節
  10:
    - 9   # 國慶日彈性
    - 10  # 國慶日
makeup_days:
  1:
    - 7   # 春節補班
  2:
    - 4   # 春節補班
    - 18  # 228 補班
  3:
    - 25  # 清明補班
  6:
    - 17  # 端午補班
  9:
    - 23  # 雙十補班
