holidays:
  1:
    - 1   # 元旦

  2:
    - 8   # 春節
    - 9   # 春節
    - 12  # 春節
    - 13  # 春節
    - 14  # 春節
    - 28  # 228
  4:
    - 4   # 清明
    - 5   # 清明
  5:
    - 1   # 勞動節
  6:
    - 10  # 端午節
  9:
    - 17  # 中秋節
  10:
    - 10  # 國慶日
makeup_days:
  2:
    - 17  # 春節補班
