holidays:
  1:
    - 1   # 元旦
    - 27  # 春節
    - 28  # 春節
    - 29  # 春節
    - 30  # 春節
    - 31  # 春節

  2:
    - 28  # 228
  4:
    - 3   # 清明
    - 4   # 清明
  5:
    - 1   # 勞動節
    - 30  # 端午節
  10:
    - 6   # 中秋節
    - 10  # 國慶日
makeup_days:
  2:
    - 8   # 春節補班
